/**
 * generated by Xtext 2.16.0
 */
package edu.univ.nantes.iot.validation;

import edu.univ.nantes.iot.validation.AbstractIotDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IotDslValidator extends AbstractIotDslValidator {
}
