/*
 * generated by Xtext 2.16.0
 */
package edu.univ.nantes.iot.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIotDslScopeProvider extends DelegatingScopeProvider {
}
