/**
 * generated by Xtext 2.16.0
 */
package edu.univ.nantes.iot.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class IotDslDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
