/*
 * generated by Xtext 2.16.0
 */
package edu.univ.nantes.iot


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class IotDslRuntimeModule extends AbstractIotDslRuntimeModule {
}
