/*
 * generated by Xtext 2.16.0
 */
package edu.univ.nantes.iot.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class IotDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("edu/univ/nantes/iot/parser/antlr/internal/InternalIotDsl.tokens");
	}
}
