/**
 * generated by Xtext 2.16.0
 */
package edu.univ.nantes.iot.ui;

import edu.univ.nantes.iot.ui.AbstractIotDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class IotDslUiModule extends AbstractIotDslUiModule {
  public IotDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
