/*
 * generated by Xtext 2.16.0
 */
package edu.univ.nantes.iot.ui.tests;

import com.google.inject.Injector;
import edu.univ.nantes.iot.ui.internal.IotActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class IotDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return IotActivator.getInstance().getInjector("edu.univ.nantes.iot.IotDsl");
	}

}
