/*
 * generated by Xtext 2.16.0
 */
package edu.univ.nantes.iot.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class IotDslUiModule extends AbstractIotDslUiModule {
}
