/**
 * generated by Xtext 2.16.0
 */
package edu.univ.nantes.iot;

import edu.univ.nantes.iot.AbstractIotDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class IotDslRuntimeModule extends AbstractIotDslRuntimeModule {
}
