/**
 * generated by Xtext 2.16.0
 */
package edu.univ.nantes.iot;

import edu.univ.nantes.iot.IotDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class IotDslStandaloneSetup extends IotDslStandaloneSetupGenerated {
  public static void doSetup() {
    new IotDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
