/*
 * generated by Xtext 2.16.0
 */
package edu.univ.nantes.iot.ui;

import com.google.inject.Injector;
import edu.univ.nantes.iot.ui.internal.IotActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IotDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(IotActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		IotActivator activator = IotActivator.getInstance();
		return activator != null ? activator.getInjector(IotActivator.EDU_UNIV_NANTES_IOT_IOTDSL) : null;
	}

}
