/**
 * generated by Xtext 2.16.0
 */
package edu.univ.nantes.iot.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import edu.univ.nantes.iot.IotDslRuntimeModule;
import edu.univ.nantes.iot.IotDslStandaloneSetup;
import edu.univ.nantes.iot.ide.IotDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class IotDslIdeSetup extends IotDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    IotDslRuntimeModule _iotDslRuntimeModule = new IotDslRuntimeModule();
    IotDslIdeModule _iotDslIdeModule = new IotDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_iotDslRuntimeModule, _iotDslIdeModule));
  }
}
