/**
 * generated by Xtext 2.16.0
 */
package edu.univ.nantes.iot.ide;

import edu.univ.nantes.iot.ide.AbstractIotDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class IotDslIdeModule extends AbstractIotDslIdeModule {
}
