/**
 * generated by Xtext 2.16.0
 */
package edu.univ.nantes.iot.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class IotDslQuickfixProvider extends DefaultQuickfixProvider {
}
