/**
 * generated by Xtext 2.16.0
 */
package edu.univ.nantes.iot.scoping;

import edu.univ.nantes.iot.scoping.AbstractIotDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class IotDslScopeProvider extends AbstractIotDslScopeProvider {
}
