/*
 * generated by Xtext 2.16.0
 */
package edu.univ.nantes.iot.ide

import com.google.inject.Guice
import edu.univ.nantes.iot.IotDslRuntimeModule
import edu.univ.nantes.iot.IotDslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class IotDslIdeSetup extends IotDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new IotDslRuntimeModule, new IotDslIdeModule))
	}
	
}
